#!/bin/sh
alias bc='bc -l'
alias vi='vim'
alias ls='ls --color=auto'
alias l='ls'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -lh'
alias lr='ll -R'
alias la='ls -lha'
alias lar='la -R'
alias lt='lstree'
alias lat='lsatree'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ack='ack-grep'
alias ackp='ack-grep --nocolor --pager="less -r"'
alias findsvn='find . -type d -name .svn'
alias findtilde='find . -name "*~"'
alias findcrlf='find . -not -type d -exec file "{}" ";" | grep CRLF'
alias findmac='find . \( -type d -name "__MACOSX" \) -o \( -type f -name ".DS_Store" \)'
alias rmmac='rm -rf `find . \( -type d -name "__MACOSX" \) -o \( -type f -name ".DS_Store" \)`'
alias rmsvn='rm -rf `find . -type d -name .svn`'
alias rmtilde='rm -f `find . -name "*~"`'
alias rmkeepsvn='rm -rf `find . -not \( -name '.svn' -type d -prune \) -type f `'
alias rmgit='rm -rf `find . -type d -name .git`'
alias rmkeepgit='rm -rf `find . -not \( -name '.git' -type d -prune \) -type f `'
alias findtextfiles='find . -type f \! -regex ".*\.\(jpg\|ico\|bmp\|jpeg\|png\|svg\|psd\|swf\|z\|tar\|zip\|bz2\|7z\|gz\|tgz\|phar\|jar\)" \! -path "*svn*" \! -path "*.git/*"'
#alias fromdos='dos2unix'
#alias todos='unix2dos'
alias fromdosr='find . -type f \! -regex ".*\.\(jpg\|ico\|bmp\|jpeg\|png\|svg\|psd\|swf\|z\|tar\|zip\|bz2\|7z\|gz\|tgz\|phar\|jar\)" \! -path "*svn*" \! -path "*.git/*" -exec fromdos {} \;'
alias todosr='find . -type f \! -regex ".*\.\(jpg\|ico\|bmp\|jpeg\|png\|svg\|psd\|swf\|z\|tar\|zip\|bz2\|7z\|gz\|tgz\|phar\|jar\)" \! -path "*svn*" \! -path "*.git/*" -exec todos {} \;'
alias clr='clear'
alias du='du -h'
alias dus='du -s'
alias df='df -hT --total'
